theme: jekyll-theme-cayman
title: Video Conferencing
description: Use Zoom for Greenpeace virtual meetings
logo: greenpeace_logo.png
zoom_logo: zoom_logo.png
show_downloads: "true"
button1_url: https://greenpeace.zoom.us/join
button2_url: http://vc.greenpeace.org/lifesize
button3_url: https://greenpeace.zoom.us/signin
button4_url: https://greenpeace.zoom.us/download
